//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationRequest
    {
        public CertificationRequest()
        {
            this.CCUser = new HashSet<CCUser>();
        }
    
        public System.Guid Id { get; set; }
        public bool IsApproved { get; set; }
        public string Decription { get; set; }
    
        public virtual ICollection<CCUser> CCUser { get; set; }
    }
}
