//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportType
    {
        public ReportType()
        {
            this.Report = new HashSet<Report>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool Proposed { get; set; }
    
        public virtual ICollection<Report> Report { get; set; }
    }
}
