//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSolution
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.Guid ReportId { get; set; }
        public System.Guid CCUserId { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual CCUser CCUser { get; set; }
    }
}
