//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.ReportSolution = new HashSet<ReportSolution>();
        }
    
        public System.Guid Id { get; set; }
        public string SiteAddress { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public System.Guid ReportTypeId { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid CCUserId { get; set; }
        public Nullable<decimal> Funds { get; set; }
        public bool IsValid { get; set; }
        public string RejectReason { get; set; }
    
        public virtual ReportType ReportType { get; set; }
        public virtual ICollection<ReportSolution> ReportSolution { get; set; }
        public virtual CCUser CCUser { get; set; }
    }
}
